:ems:
  :ems_cloud_automation_manager:
    :blacklisted_event_names: []
    :event_handling:
      :event_groups:
:http_proxy:
  :cloud_automation_manager:
    :host:
    :password:
    :port:
    :user:
:workers:
  :worker_base:
    :queue_worker_base:
      :ems_refresh_worker:
        :ems_refresh_worker_cam_configuration: {}
