:ems:
  :ems_cloud_automation_manager:
    :blacklisted_event_names: []
    :event_handling:
      :event_groups:
:http_proxy:
  :cloud_automation_manager:
    :host:
    :password:
    :port:
    :user:
